# render.yaml
services:
  - type: web
    name: telegram-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    port: 8080
    envVars:
      - key: PORT
        value: 8080
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/www/html
      sizeGB: 1